version: '3'
services:
  app:
    build: .
    ports:
      - "4005:4005"
    working_dir: /app
    command: ["node", "index.js"]
    # volumes:     
    #   - /home/sirius5/e-commerce/E-commerce:/app      
    #   - /home/sirius5/e-commerce/E-commerce/node_modules
  redis:
    image: "redis:latest"
    ports:
      - "6380:6379"